<a href="https://colab.research.google.com/github/Santoshsai007/Santoshsai007/blob/main/JOB_A_THON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [250]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [251]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [252]:
dftrain=pd.read_csv("/content/drive/MyDrive/job_a_thon_nov_2021.csv")

In [253]:
dftrain.head()

MMM-YY  Emp_ID  Age  ... Designation Total Business Value Quarterly Rating
0  2016-01-01       1   28  ...           1              2381060                2
1  2016-02-01       1   28  ...           1              -665480                2
2  2016-03-01       1   28  ...           1                    0                2
3  2017-11-01       2   31  ...           2                    0                1
4  2017-12-01       2   31  ...           2                    0                1

[5 rows x 13 columns]

In [254]:
dftest=pd.read_csv("/content/drive/MyDrive/job_a_thon_test.csv")

In [255]:
dftrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19104 entries, 0 to 19103
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MMM-YY                19104 non-null  object
 1   Emp_ID                19104 non-null  int64 
 2   Age                   19104 non-null  int64 
 3   Gender                19104 non-null  object
 4   City                  19104 non-null  object
 5   Education_Level       19104 non-null  object
 6   Salary                19104 non-null  int64 
 7   Dateofjoining         19104 non-null  object
 8   LastWorkingDate       1616 non-null   object
 9   Joining Designation   19104 non-null  int64 
 10  Designation           19104 non-null  int64 
 11  Total Business Value  19104 non-null  int64 
 12  Quarterly Rating      19104 non-null  int64 
dtypes: int64(7), object(6)
memory usage: 1.9+ MB


In [256]:
check1=dftrain[dftrain["LastWorkingDate"].notnull()]

In [257]:
check3=dftrain.groupby("Emp_ID")["Total Business Value"].sum()

In [258]:
check4=dftrain.groupby("Emp_ID")["Quarterly Rating"].sum().reset_index(name="rating")

In [259]:
x=dftrain["Emp_ID"].value_counts()

In [260]:
x.index=x.index.set_names("Emp_ID")

In [261]:
x=x.reset_index(name="count")

In [262]:
check3=check3.reset_index()

In [263]:
check3=check3.join(x.set_index("Emp_ID"),on="Emp_ID")

In [264]:
check5=check3.join(check4.set_index("Emp_ID"),on="Emp_ID")

In [265]:
check5["Avg_Quarterly Rating"]=check5["rating"]/check5["count"]

In [266]:
check6=check5.drop(["rating","count"],axis=1)

In [267]:
check6.rename(columns={"Total Business Value":"Total_Business_Value"},inplace=True)

In [268]:
dftrain1=dftrain.drop_duplicates(subset=["Emp_ID"],keep='first')

In [269]:
dftrain1.shape

(2381, 13)

In [270]:
check7=check6.join(dftrain1.set_index("Emp_ID"),on="Emp_ID")

In [271]:
check7.head()

Emp_ID  Total_Business_Value  ...  Total Business Value Quarterly Rating
0       1               1715580  ...               2381060                2
1       2                     0  ...                     0                1
2       4                350000  ...                     0                1
3       5                120360  ...                     0                1
4       6               1265000  ...                     0                1

[5 rows x 15 columns]

In [272]:
check8=check7.drop(["Total Business Value","Quarterly Rating","MMM-YY"],axis=1)

In [273]:
check8["LastWorkingDate"].fillna("2017-12-31",inplace=True)

In [274]:
check8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2381 entries, 0 to 2380
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Emp_ID                2381 non-null   int64  
 1   Total_Business_Value  2381 non-null   int64  
 2   Avg_Quarterly Rating  2381 non-null   float64
 3   Age                   2381 non-null   int64  
 4   Gender                2381 non-null   object 
 5   City                  2381 non-null   object 
 6   Education_Level       2381 non-null   object 
 7   Salary                2381 non-null   int64  
 8   Dateofjoining         2381 non-null   object 
 9   LastWorkingDate       2381 non-null   object 
 10  Joining Designation   2381 non-null   int64  
 11  Designation           2381 non-null   int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 223.3+ KB


In [275]:
check8['Dateofjoining'] =  pd.to_datetime(check8['Dateofjoining'], infer_datetime_format=True)

In [276]:
check8['LastWorkingDate'] =  pd.to_datetime(check8['LastWorkingDate'], infer_datetime_format=True)

In [277]:
check8["Tenure"]=(check8['LastWorkingDate']-check8['Dateofjoining']).dt.days

In [278]:
check8["Growth"]=check8["Designation"]-check8["Joining Designation"]

In [279]:
check8.head()

Emp_ID  Total_Business_Value  ...  Tenure  Growth
0       1               1715580  ...     738       0
1       2                     0  ...      55       0
2       4                350000  ...     389       0
3       5                120360  ...     722       0
4       6               1265000  ...     153       0

[5 rows x 14 columns]

In [280]:
check9=check8.drop(["Dateofjoining","LastWorkingDate"],axis=1)

In [281]:
check9.head()

Emp_ID  Total_Business_Value  ...  Tenure  Growth
0       1               1715580  ...     738       0
1       2                     0  ...      55       0
2       4                350000  ...     389       0
3       5                120360  ...     722       0
4       6               1265000  ...     153       0

[5 rows x 12 columns]

In [282]:
check9.City.nunique()

29

In [283]:
check10_dummy=check9[["Gender","Education_Level","City"]]

In [284]:
check10_dummy=pd.get_dummies(check10_dummy)

In [285]:
check10_dummy.head()

Gender_Female  Gender_Male  ...  City_C8  City_C9
0              0            1  ...        0        0
1              0            1  ...        0        0
2              0            1  ...        0        0
3              0            1  ...        0        1
4              1            0  ...        0        0

[5 rows x 34 columns]

In [286]:
check11_scale=check9.drop(["Gender","Education_Level","City"],axis=1)

In [287]:
from sklearn.preprocessing import MinMaxScaler

In [288]:
mm=MinMaxScaler()

In [289]:
check11_scale_=mm.fit_transform(check11_scale)

In [290]:
check11_scale_=pd.DataFrame(check11_scale_,columns=check11_scale.columns)

In [291]:
check11_scale_

Emp_ID  Total_Business_Value  ...    Tenure  Growth
0     0.000000              0.032064  ...  0.260685    0.00
1     0.000359              0.014326  ...  0.019428    0.00
2     0.001076              0.017944  ...  0.137407    0.00
3     0.001435              0.015570  ...  0.255034    0.00
4     0.001794              0.027405  ...  0.054045    0.00
...        ...                   ...  ...       ...     ...
2376  0.998565              0.239197  ...  0.672201    0.25
2377  0.998924              0.014326  ...  0.044154    0.00
2378  0.999282              0.043432  ...  0.312257    0.00
2379  0.999641              0.024436  ...  0.315789    0.00
2380  1.000000              0.038088  ...  0.072766    0.00

[2381 rows x 9 columns]

In [292]:
combinedf=pd.concat([check10_dummy,check11_scale_],axis=1)

In [293]:
combinedf=combinedf.drop("Emp_ID",axis=1)

In [294]:
combinedf.shape

(2381, 42)

In [295]:
from sklearn.cluster import KMeans

In [296]:
k_means = KMeans(init = "k-means++", n_clusters = 2, n_init = 12)

In [297]:
k_means.fit(combinedf)
labels = k_means.labels_
print(labels)

[0 0 0 ... 0 1 0]


In [298]:
labels.shape

(2381,)

In [299]:
check9["labels"]=labels

In [300]:
check9.labels.value_counts()

0    1404
1     977
Name: labels, dtype: int64

In [301]:
dftest.head()

Emp_ID
0     394
1     173
2    1090
3     840
4     308

In [302]:
prediction.head()

Emp_ID  Total_Business_Value  ...  labels_agg  labels_fclust
0     394              27458220  ...           1              1
1     173              19866290  ...           0              0
2    1090              50382490  ...           0              0
3     840              17134040  ...           1              1
4     308              58024490  ...           0              0

[5 rows x 14 columns]

In [303]:
prediction_.to_csv("job1.csv",index=False)

In [304]:
from scipy import ndimage 
from scipy.cluster import hierarchy 
from scipy.spatial import distance_matrix 
from sklearn.cluster import AgglomerativeClustering 

In [305]:
x=np.array(combinedf)

In [306]:
import scipy
leng = x.shape[0]
D = scipy.zeros([leng,leng])
for i in range(leng):
    for j in range(leng):
        D[i,j] = scipy.spatial.distance.euclidean(x[i], x[j])
D

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.        , 1.51794013, 1.55499192, ..., 2.08386386, 2.00886011,
        1.4749222 ],
       [1.51794013, 0.        , 1.45574097, ..., 2.07150958, 2.06094142,
        1.47997874],
       [1.55499192, 1.45574097, 0.        , ..., 2.02738518, 2.08553932,
        1.52712581],
       ...,
       [2.08386386, 2.07150958, 2.02738518, ..., 0.        , 2.52038774,
        2.0743355 ],
       [2.00886011, 2.06094142, 2.08553932, ..., 2.52038774, 0.        ,
        2.06242323],
       [1.4749222 , 1.47997874, 1.52712581, ..., 2.0743355 , 2.06242323,
        0.        ]])

In [307]:
import pylab
import scipy.cluster.hierarchy
Z = hierarchy.linkage(D, 'complete')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  This is separate from the ipykernel package so we can avoid doing imports until


In [308]:
from scipy.cluster.hierarchy import fcluster
max_d = 3
clusters = fcluster(Z, max_d, criterion='distance')
clusters

array([562, 469, 556, ..., 309, 964, 586], dtype=int32)

In [309]:
from scipy.cluster.hierarchy import fcluster
k = 2
clusters = fcluster(Z, k, criterion='maxclust')
clusters


array([1, 1, 1, ..., 1, 2, 1], dtype=int32)

In [310]:
check9["labels_fclust"]=clusters

In [311]:
from sklearn.metrics.pairwise import euclidean_distances
dist_matrix = euclidean_distances(x,x) 
print(dist_matrix)

[[0.         1.51794013 1.55499192 ... 2.08386386 2.00886011 1.4749222 ]
 [1.51794013 0.         1.45574097 ... 2.07150958 2.06094142 1.47997874]
 [1.55499192 1.45574097 0.         ... 2.02738518 2.08553932 1.52712581]
 ...
 [2.08386386 2.07150958 2.02738518 ... 0.         2.52038774 2.0743355 ]
 [2.00886011 2.06094142 2.08553932 ... 2.52038774 0.         2.06242323]
 [1.4749222  1.47997874 1.52712581 ... 2.0743355  2.06242323 0.        ]]


In [312]:
Z_using_dist_matrix = hierarchy.linkage(dist_matrix, 'complete')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  """Entry point for launching an IPython kernel.


In [313]:
agglom = AgglomerativeClustering(n_clusters = 2, linkage = 'complete')
agglom.fit(dist_matrix)

agglom.labels_

/usr/local/lib/python3.7/dist-packages/sklearn/cluster/_agglomerative.py:542: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  out = hierarchy.linkage(X, method=linkage, metric=affinity)


array([1, 1, 1, ..., 1, 0, 1])

In [314]:
check9["labels_agg"]=agglom.labels_

In [315]:
check9["labels_fclust"].replace(2,0,inplace=True)

In [316]:
check9.head()

Emp_ID  Total_Business_Value  ...  labels_fclust  labels_agg
0       1               1715580  ...              1           1
1       2                     0  ...              1           1
2       4                350000  ...              1           1
3       5                120360  ...              1           1
4       6               1265000  ...              0           0

[5 rows x 15 columns]

In [317]:
check9["labels"].value_counts()

0    1404
1     977
Name: labels, dtype: int64

In [318]:
check9["labels_fclust"].value_counts()

1    1404
0     977
Name: labels_fclust, dtype: int64

In [319]:
check9["labels_agg"].value_counts()

1    1404
0     977
Name: labels_agg, dtype: int64

In [320]:
prediction=dftest.join(check9.set_index("Emp_ID"),on="Emp_ID")

In [321]:
prediction_kmean=prediction[["Emp_ID","labels"]]

In [322]:
prediction_.to_csv("job1.csv",index=False)

In [323]:
prediction_fclust=prediction[["Emp_ID","labels_fclust"]]

In [324]:
prediction_fclust.to_csv("job_fclust.csv",index=False)

In [325]:
prediction_agg=prediction[["Emp_ID","labels_agg"]]

In [326]:
prediction_agg.to_csv("job_agg.csv",index=False)

In [327]:
from sklearn.cluster import DBSCAN

In [407]:
db = DBSCAN(eps=0.85, min_samples=30).fit(combinedf)

In [408]:
labels=db.labels_

In [409]:


realClusterNum=len(set(labels)) - (1 if -1 in labels else 0)
clusterNum = len(set(labels))

In [410]:

clusterNum

2

In [411]:
labels=pd.DataFrame(labels,columns=["dbscan"])

In [412]:
labels.dbscan.value_counts()

-1    2348
 0      33
Name: dbscan, dtype: int64